version: '3.8'
services:
  keycloak:
    image: quay.io/keycloak/keycloak:24.0.2
    container_name: keycloak
    hostname: keycloak
    command:
      - start-dev
      - --import-realm
      - --http-port=8080
      - --http-relative-path=/auth
    volumes:
      - ./realm-config:/opt/keycloak/data/import
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin1234
    ports:
      - "9191:8080"
    restart: always
