services:
  - name: keycloak
    type: web
    runtime: docker
    plan: standard  # Ensure this plan supports the necessary resources
    dockerContext: .  # Your current directory where Dockerfile is located
    dockerfilePath: ./Dockerfile
    envVars:
      - key: KEYCLOAK_ADMIN
        value: admin
      - key: KEYCLOAK_ADMIN_PASSWORD
        value: admin1234
      - key: KEYCLOAK_HTTP_PORT
        value: "9191"  # Ensures Keycloak listens on port 9191
    disk:
      name: keycloak-data
      mountPath: /opt/keycloak/data/import
      sizeGB: 1
    healthCheckPath: /health/live  # Standard health check path for Keycloak
    autoDeploy: true
    ports:
      - "9191"  # Bind the port externally
 